_target_: src.models.bowl_detection_module.BowlDetectionModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.faster_rcnn.FasterRCNN
  num_classes: 3  # 1 class + background
  pretrained: True

compile: false 