_target_: src.models.bowl_detection_module.BowlDetectionModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.retinanet.RetinaNet
  num_classes: 3 # 2 foreground classes (bowl, empty bowl) + 1 background
  pretrained: true

# compile model for faster training with pytorch 2.0
compile: false
