# @package _global_

defaults:
  - _self_
  - data: bowl # choose datamodule with `test_dataloader()` for evaluation
  - model: retinanet
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: weights/2025-06-09_07-07-26/checkpoints/epoch_009.ckpt
