# @package _global_

defaults:
  - _self_
  - data: bowl # choose datamodule with `test_dataloader()` for evaluation
  - model: retinanet
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval_visualize"

tags: ["inference", "visualization"]

ckpt_path: weights/2025-06-09_07-07-26/checkpoints/epoch_009.ckpt

# Visualization settings
visualize: true
output_dir: "inference_visualizations"
confidence_threshold: 0.7
nms_threshold: 0.3
