# @package _global_

defaults:
  - _self_
  - data: bowl # choose datamodule with `test_dataloader()` for evaluation
  - model: bowl_object_detection
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2025-05-21_01-54-25/checkpoints/last.ckpt
